mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static 
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    
    path('',views.posts_list, name="list"),
    path('new-post',views.post_new, name="new-post"),
    
    #slug adalah konverter jalur, untuk memberi tau django bahwa nilai yang ditangkpak harus sesuai dengan format slug
    #slug: adalah nama parameter yang akan diteruskan ke view, dalam hal ini slug dari UTL akan tersedia dalam view sebagai argumen bernama slug
    path('<slug:slug>',views.post_page, name="page"),
   
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    
    path('register/',views.register_view, name="register"),
    path('login/',views.login_view, name="login"),
    path('logout/',views.logout_view, name="logout"),

    

]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None) 
        # karena dlama database butuh foreign key
        # on_delete dibutuhkan karena untuk memberi tahu database bagaimana meng-handle data
        # jika relationship (on_delete) nya dihapus.
        # CASCADE berati "Ok jika user dihapus maka hapus semua post nya juga."
        # Sehingga tidak ada "broken-relationship"
    def __str__(self):
        return self.title
    

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'banner']

mywebsite/views.py
#from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse("Hello World! ")
    return render(request, 'home.html')

def about(request):
    #return HttpResponse("About Page")
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import redirect, render
from.models import Post
from django.contrib.auth.decorators import login_required
from . import forms
#from django.http import HttpResponse
# Create your views here.

def posts_list(request):
    #posts = Post.objects.all().order_by('-date') #minus buat urutan terakkhir
    posts = Post.objects.all()
    return render(request, 'posts/posts_list.html', {'posts' :
    posts})

def post_page(request, slug):
    #return HttpResponse(slug)
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post' :
    post})

def post_new(request):
    return render(request, 'posts/post_new.hmtl')

# logic untuk cek kalo user udah login atau belum, kalau udah bisa post_new
@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            # save with user
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

users/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == "POST": 
        form = UserCreationForm(request.POST) 
        if form.is_valid(): 
            login(request, form.save()) 
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", { "form": form })

# ini logic nya if request post habis itu muncul form,
# habis itu isi form, terus di cek kalau valid dalam arti tidak ada username yang sama atau pass salah maka di save, 
# dan akan kembali ke list post. else berati gada data yang di isi, tapi tetap ada form


def login_view(request):
    if request.method == "POST": 
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # LOGIN HERE
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", { "form": form })


def logout_view(request):
    if request.method == "POST": 
        logout(request)
        return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/logout.html", { "form": form })

posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
    <section>
        <h1> New Post! </h1>
        <form
            class="form-with-validation" 
            action="{% url 'posts:new-post' %}" 
            method="post"
            enctype="multipart/form-data"> <!--biar ada gambar juga ga cuma form biasa-->
                {% csrf_token %}
                {{ form }}
                <button class="form-submit"> Add Post </button>
        </form>
    </section> 
{% endblock  %}

posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
{{ post.title }} 
{% endblock %}

{% block content %}
    <section class="post-page">

        <img 
        class="banner"
        src="{{ post.banner.url }}"
        alt="{{ post.title }}"
        />

        <h1> {{ post.title }} </h1>
        <p>{{ post.date|timesince  }} ago</p>
        <p>{{ post.body|linebreaks|urlize }}</p>   
        <p><b> Word Count: {{ post.body|wordcount}}</b></p>
    </section> 
{% endblock  %}
# Gue pake template buat ngerapiin article seperti timesince,linebreaks dll
#https://dev.to/vijaysoni007/my-favorite-django-template-filters-2nen

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts 
{% endblock %}

{% block content %}
<section>
    <h1>Posts</h1>

    {% for post in posts %}
        <article class="post">
            <h2>
                <a href="{% url 'posts:page' slug=post.slug %}">
                {{ post.title|title }} 
                </a>
            </h2>
            <p>{{ post.date|timesince  }} ago by {{ post.author }}</p>
            <p>{{ post.body|truncatewords:10}}</p>   
            
        </article>
    {% endfor %}

</section> 
{% endblock  %}
# Gue pake template buat ngerapiin article seperti timesince,linebreaks dll
#ttps://dev.to/vijaysoni007/my-favorite-django-template-filters-2nen

templates/about.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <div class="about-content">
        <h1>About</h1>
        
    
    <h2>Dema </h2>
    <p>The perplexities of the Dema horizon didn't occur to me until my ninth year. It was then that I began to contemplate the existential, and decide what type of impression I wanted my life to make. Naturally, to fuel my hope, I looked out upon the distance of the land that had cultivated me, only this time with a new awareness of the obstruction that my youthful ignorance had allowed me to overlook. Was it there the whole time? How had I not seen something so obvious? I am reminded of the moment daily, as the idealization directly collides with a unique hope for my own future. As a child, I looked upon Dema with wonder, today, I am wrought with frustration, as I spend each day squinting for a glimpse of the top of the looming wall that has kept us here. It was upon my ninth year that I learned that Dema wasn’t my home. This village, after all of this time, was my trap.

        Before I became realized, I had deep affection for Dema. There was a wonderful structure to the city that put my cares to rest. Streets and locations were dependable, and the responsibilities of the day seemed to be accomplished with minimal effort. Once a task was taught and understood, we delighted in our ability to complete our obligations timely, and felt secure in knowing tomorrow’s duties would be accomplished with the same efficiency. We all worked to represent our bishop with honor, and knew that each inhabitant of our region had a like-minded dedication to consistency.
        
        Keons embodied the spirit of this dedication. Of Dema’s nine bishops, Keons was revered as unwavering and forthright, possessing the ability to achieve focus that was rare for most on our region. We all admired him, and felt honored to be inhabitants his region. While we had heard legend of the ruthlessness of other bishops, Keons possessed a stoic demeanor unlike anyone I had ever met, and we were all proud to serve.
        
        - Clancy</p>
{% endblock  %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <h1>Check out my  <a href="/about">About</a> page!</h1>
{% endblock  %}

#iseng aja ini mah ngetest doang

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title%}
        Django App
        {% endblock %}
    </title>

    <script src="{% static 'js/main.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"></head>
<body>
    <nav class="navigation-bar">
       
        <h1>CliqueOrg.info</h1>
        <a href="/">
            <span role="img" aria-label="Home" title="Home">🏠</span>
        </a> |
        <a href="/about" title="About">💬</a> |
        <a href="{% url 'posts:list' %}" title="Posts">📰</a> |
        
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post'%}" title="New Post">🆕</a> |
            
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button" title="Logout">😊</button>
            </form>
        {% else %}
            <a href="{% url 'users:register' %}" title="Register">✏️</a> |
            <a href="{% url 'users:login' %}" title="Login">🔑</a> |
        {% endif %}
        
    </nav>
    
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}

{% block content %}
    <h2>User Login</h2>
    <form 
        class="form-with-validation"
        action="/users/login/" 
        method="post">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
            {% endif %}
            <button class="form-submit">Login</button>
    </form>
{% endblock  %}

users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    User Register
{% endblock %}

{% block content %}
    <h2>Register a new Users</h2>
    <form 
        class="form-with-validation"
        action="/users/register/" 
        method="post">
             #csrf untuk keamanan, agar no one pretending to be me while submit by django
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Submit</button>


    </form>
{% endblock  %}